name: Build VMK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Thích thì build thôi'
        required: false
        default: 'Manual build'

jobs:
  build:
    name: Build on Ubuntu 22.04
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          extra-cmake-modules \
          libfcitx5core-dev \
          libfcitx5config-dev \
          libfcitx5utils-dev \
          libinput-dev \
          libudev-dev \
          g++ \
          golang \
          hicolor-icon-theme \
          pkg-config \
          libx11-dev

    - name: Create tarball structure
      run: |
        mkdir -p dist
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib .
        make
        make install DESTDIR=$(pwd)/dist

        ls -R dist/

    - name: Compress Artifact
      run: |
        tar -czf fcitx5-vmk-${{ github.ref_name }}.tar.gz -C dist .

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: fcitx5-vmk-${{ github.ref_name }}.tar.gz
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref }}
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}